module.exports = Object.assign(
  {},
  require('./coin'),
  require('./coins'),
  require('./coin-events'),
  require('./coin-twitter'),
  require('./exchanges'),
  require('./historical-tickers'),
  require('./market-overview'),
  require('./markets'),
  require('./ohlc'),
  require('./person'),
  require('./tags'),
  require('./tag'),
  require('./tickers'),
)